-- basic example tabel
create table text_table
(
    id uuid primary key default gen_random_uuid(),
    de text,
    fr text,
    it text,
    en text
);

-- create indexed without the defined helper function for a basic example
create index text_table_de_idx on text_table using GIN (to_tsvector('german', de));
create index text_table_fr_idx on text_table using GIN (to_tsvector('french', fr));
create index text_table_it_idx on text_table using GIN (to_tsvector('italian', it));
create index text_table_en_idx on text_table using GIN (to_tsvector('english', fr));


insert into text_table(de, en)
values ( 'Lord Vetinari hat seine eigenen Vorstellungen von Personalrekrutierung und passgenauer Stellenbesetzung. Er stellt selbst verurteilte Verbrecher in Dienst, sofern er bei ihnen das Potential erkennt, Ankh-Morpork zu dienen. Seine Menschenkenntnis irrt dabei selten.

Die Stadt braucht einen neuen Postminister. Vetinari verurteilt den Gentleman-Betrüger Albert Spangler zum Tode und lässt ihn hängen. Nachdem Feucht von Lipwig, wie Spangler wirklich heißt, überraschenderweise wieder zu sich kommt, stellt der Patrizier ihn vor die Wahl, entweder die Stelle des Postministers anzunehmen oder durch einen Sturz endgültig zu sterben. Feucht entscheidet sich vorerst für den neuen Beruf, ergreift aber bei der erstbesten Gelegenheit die Flucht und galoppiert aus der Stadt. Allerdings hat Vetinari bereits den Golem Herr Pumpe als seinen Bewährungshelfer eingesetzt, der Feucht anhand seiner karmischen Signatur Tag und Nacht verfolgt. Feucht erkennt seine Ausweglosigkeit und tritt seine neue Stelle an.

Seit 20 Jahren hat kein Brief das Postamt mehr verlassen. Die nicht zugestellten Briefe verstopfen das gesamte heruntergekommene Gebäude. Von seinen beiden einzigen Angestellten, dem alten Junior-Postboten Herrn Grütze und dem jungen Postbotenanwärter Stanley, erfährt Feucht, dass die Installation der innovativen Sortieranlage des Absolut Bekloppten Johnson das Ende eingeläutet hatte.

Widerwillig beginnt Feucht, den Postdienst neu zu organisieren und nimmt sich zuerst den ramponierten Schriftfries über dem Eingang vor. Er überredet Hugo S., den Inhaber des gleichnamigen Friseursalons, die Buchstaben seines Ladenschildes inklusive einer großzügigen Spende ans Postamt zurückzugeben. Dann stellt er dem Gemüsehändler Parker einen der uralten Briefe zu.

Die Geheimgesellschaft der Postboten prüft Feucht – den „Unfrankierten Mann“ – und erkennt ihn dann als tatsächlichen Postminister an. Die Dinge kommen in Bewegung und Post wird zugestellt. Allerdings sind die Zusteller nur wenige alte Postpensionäre, die den Tücken des Postbotenalltags nicht mehr gewachsen sind. Deswegen sucht Feucht die Golemstiftung von Adora Belle Liebherz auf. Feuchts Werbung um diese schöne, aber zynische junge Frau ist ein weiterer Erzählstrang des Romans.

Zunächst übernimmt er von ihrer Stiftung alle freien Golems, malt sie blau und golden an und stellt sie den alten Zustellern als Gehilfen zur Seite. Zweieinhalb Meter große Postboten erregen Aufsehen und das will Feucht erreichen. Er selbst trägt inzwischen einen goldenen Anzug und eine goldene, mit Flügeln versehene Kappe. Seine neueste Erfindung, die Briefmarke, erfreut sich sofort größter Beliebtheit. Sie wird sogar als inoffizielles Zahlungsmittel verwendet. Nun werden nicht mehr nur alte Briefe zugestellt, es kommt ständig neue, frische Post herein und nicht nur für Ankh-Morpork, sondern für alle Städte im Umland.

In dieser Situation sieht sich der skrupellose Unternehmer Reacher Gilt gestört. Durch feindliche Übernahme ist er der Besitzer des „Großen Strangs“ geworden, der Betreibergesellschaft der Semaphoren. Der Erfolg der Post droht ein Konkurrent der Telegraphie zu werden. Besonders weil seit Gilts Übernahme die Zuverlässigkeit zugunsten des Profits sinkt. Gilt ordnet an, den störenden Wettbewerber zu beseitigen. Zwar kann Feucht diesem Anschlag entgehen, doch dafür brennt das Postamt bis auf die Grundmauern nieder.

Nach Feuchts persönlicher Begegnung mit Reacher Gilt weiß er, dass jener ein noch viel größerer Betrüger ist als es Feucht in seinen besten Zeiten je war. Nun erwacht Feuchts Ehrgeiz, diesen Titan von einem Betrüger zur Strecke zu bringen. Er verspricht Adora Belle Liebherz, deren Familie von Gilt in den Ruin getrieben wurde, den Vorsitzenden der Klackergesellschaft binnen einer Woche zu vernichten.

Für den Aufbau des Postamts will Feucht sein früher ergaunertes Vermögen einsetzen. Um es reinzuwaschen, schreibt er in aller Öffentlichkeit einen Brief an die Götter, in dem er um Beistand bittet. Danach gibt er vor, in einem Traum den Lageplan für einen Schatz von 150.000 Ankh-Morpork-Dollar erhalten zu haben.

Als Nächstes fordert Feucht die Konkurrenten vom Großen Strang zu einem Wettstreit heraus. Er wettet, mit der Postkutsche eine Nachricht schneller ins 2000 Meilen entfernte Gennua bringen zu können als die Klacker. Der Postminister kann zwar auf Unterstützung des „Rauchenden Gnu“ bauen, eine Gruppe aus drei Hackern, die den gesamten Strang ausschalten könnten, wenn Feucht das von ihnen verlangte, sein Plan ist allerdings lediglich Reacher Gilt auszuschalten.

Bei der Wettfahrt sollen die Hacker die ursprüngliche Nachricht austauschen. Feucht speist eine Anklageschrift gegen den Vorstand des Großen Strangs ins Klackersystem ein, die scheinbar von den verstorbenen Opfern der Gesellschaft stammt. Dies führt zur Verhaftung von Reacher Gilt und der Große Strang wird zunächst staatlicher Aufsicht unterstellt und provisorisch im Verantwortungsbereich des Postministers angesiedelt. ',
    'As with many of the Discworld novels, the story takes place in Ankh-Morpork, a powerful city-state based on the historical and modern settings of various metropolises like London or New York City. The protagonist of the story is Moist von Lipwig, a skilled con artist who was to be hanged for his crimes, but saved at the last moment by the cunning and manipulative Patrician Havelock Vetinari, who has Moist''s death on the scaffold faked.

In his office, Vetinari then presents Moist with two options: he may accept a job offer to become Postmaster of the city''s rundown Postal Service or he may choose to walk out of the door and never hear from Vetinari again. As exiting through the door in question would lead to a fatal drop, Moist decides to accept the job.

After a thwarted attempt at escape, Moist is brought to the Post Office by his parole officer Mr Pump, a golem. It turns out that the Post Office has not functioned for decades, and the building is full of undelivered mail, concealed under a layer of pigeon dung. Only two employees remain: the aged Junior Postman Tolliver Groat and his assistant Stanley Howler.

Meanwhile, Vetinari is holding a meeting with the board executives of the Grand Trunk Company, a company that owns and operates a system of visual telegraph towers known as "clacks". He notes that since they have taken full control, the quality of service had gone down considerably. Despite unnerving most of the board, Vetinari fails to make headway, especially with its chairman, Reacher Gilt. It is rumored that, from his penthouse office in Tump Tower, Reacher Gilt plans to usurp Vetinari as Patrician.

As Moist attempts to revitalise the postal service, he discovers that over the few months before taking the job, a number of his predecessors have predeceased in the building within weeks of each other in unusual circumstances. He also discovers that the mail inside the building has taken on a life of its own, and is nearly suffocated as a result.

Moist introduces postage stamps to Ankh-Morpork, hires golems to deliver the mail, and finds himself competing against the Grand Trunk Clacks line. He meets and falls in love with the chain-smoking, golem-rights activist, Adora Belle Dearheart, and the two begin a relationship by the end of the book. Dearheart is the daughter of the Clacks founder Robert Dearheart, though the company was taken away from her father and the other founders by tricky financial manoeuvring. She still has useful contacts amongst the clacks operators.

The unscrupulous Clacks chairman, Reacher Gilt, sets a banshee assassin (Mr Gryle) on the Postmaster, but only manages to burn down much of the Post Office building. The banshee dies when he is flipped onto the space-warping sorting machine. Lipwig makes an outrageous wager that he can deliver a message to Genua, 2000 miles from Ankh-Morpork, faster than the Grand Trunk can. "The Smoking Gnu", a group of clacks-crackers, sets up a plan to send ''the woodpecker'' (a Discworld equivalent to a killer poke) into the clacks system that will destroy the machinery, halting the message that Lipwig will race against. Lipwig talks the Gnu out of it, wanting to leave the semaphore towers standing. Instead, Lipwig and the Gnu, using Trunk documents in Adora Belle''s possession, intercept the message and replace it with a message from the dead which serves as a confession of guilt by the Trunk. This plan succeeds.

Gilt is soon arrested and finds himself in front of the Patrician, offered a similar choice to the one Moist faced in the beginning of the book: run the mint or exit the room. Gilt, however, chooses to walk through the door to his death. '),
('Einer „anthropomorphen Personifizierung“ wie Tod ist es quasi in die Wiege gelegt, sich für den Gegenstand zu interessieren, der ihn in der Welt manifest hat werden lassen. Tods Interesse an allen Aspekten des menschlichen Wesens ist seiner Gestalt also inhärent. In diesem Roman stößt er auf das Konzept „Ausbildung“ und sucht sich einen Lehrling. Er findet ihn in Mortimer, dem schlaksigen, rothaarigen Sohn eines ambitionierten reanuellen Wein-Bauern (jemand, der heute Wein anbaut, der gestern schon getrunken wurde).

Mort ist ein extremer Tollpatsch. Kein anderer Handwerksmeister will ihn ausbilden. Tod setzt andere Prioritäten. Er lehrt ihn sein „Handwerk“ und Mort macht seine Sache anfangs durchaus gut. So gut, dass Tod die Vorteile, einen formidablen Stellvertreter zu haben, dazu nutzt seine Humanstudien voranzutreiben, um beispielsweise das Vergnügen des Trockenfliegen-Angelns zu erleben.

Mort indes, bei weitem noch nicht gefestigt in der Erfüllung der Pflicht, gibt seinem Mitgefühl und seinem Gerechtigkeitsempfinden nach und weigert sich, der hübschen Prinzessin Keli den Tod zu bringen. Damit ändert er den Lauf der Geschichte und bringt die ganze Scheibenwelt in Gefahr.

Als Tod ihm auf die Schliche kommt, trägt das nur bedingt zu seiner Erheiterung bei. Er bestraft Mort mit dem Tod. Als er jedoch erkennt, wie unglücklich seine Adoptiv-Tochter Ysabell mit dieser Entscheidung ist, ändert er die Realität, verheiratet die beiden miteinander und schickt sie in die wirkliche Welt zurück. ',
'As a teenager, Mort has a personality and temperament that makes him unsuited to the family farming business. Mort''s father Lezek takes him to a local hiring fair in the hope that Mort will land an apprenticeship; not only would this provide a job for his son, but it would also make his son''s propensity for thinking, someone else''s problem. Just before the last stroke of midnight, Death arrives and takes Mort on as an apprentice (though his father thinks he has been apprenticed to an undertaker). Death takes Mort to his domain, where he meets Death''s elderly manservant Albert, and his adopted daughter Ysabell. Mort later accompanies Death as he travels to collect the soul of a king, who is due to be assassinated by the scheming Duke of Sto Helit. After Mort unsuccessfully tries to prevent the assassination, Death warns him that all deaths are predetermined, and that he cannot interfere with fate.

Later on, Death assigns Mort to collect the soul of Princess Keli, daughter of the murdered king, but he instead kills the assassin the Duke had sent after her. Keli lives, but shortly after the assassin''s death people begin acting as if something had happened without knowing why, such as a solemn song being played. She soon finds that the rest of the world no longer acknowledges her existence at all unless she confronts them and even then only in a confused manner which is forgotten immediately after. She subsequently employs the wizard Igneous Cutwell, who is able to see her as he is trained to see things that are invisible to normal people (like death) to make her existence clear to the public. Mort eventually discovers that his actions have created an alternate reality in which Keli lives, but he also learns that it is being overridden by the original reality and will eventually cease to exist, killing Keli. While consulting Cutwell, Mort sees a picture of Unseen University''s founder, Alberto Malich, noting that he bears a resemblance to Albert.

Mort and Ysabell travel into the Stack, a library in Death''s domain that holds the biographies of everyone who has ever lived, in order to investigate Albert, eventually discovering that he is indeed Malich. They further learn that Malich had feared monsters waiting for him in the afterlife, and performed a reversed version of the Rite of AshkEnte in the hope of keeping Death away from him. However, the spell backfired and sent him to Death''s side, where he has remained in order to put off his demise. During this time, Death, yearning to relish what being human is like, travels to Ankh-Morpork to indulge in new experiences, including getting drunk, dancing, gambling and finding a job. Mort in turn starts to become more like Death, adopting his mannerisms and aspects of his personality, while his own is slowly overridden.

Death''s absence forces Mort to collect the next two souls, who are both located on separate parts of the Disc, and due to die on the same night that the alternate reality will be destroyed. Before he and Ysabell leave to collect the souls, Mort uses the part of Death within him to force Albert to provide a spell that will slow down the alternate reality''s destruction. After Mort and Ysabell leave, Albert returns to Unseen University, under the identity of Malich. His eagerness to live on the Disc is reinvigorated during this time, and he has the wizards perform the Rite of AshkEnte in the hope of finally escaping Death''s grasp. The ritual summons both Death and the part of Death that had been taking Mort over, restoring him to normal. Unaware of Albert''s treachery, Death takes him back into his service, the Librarian preventing the wizard''s escape.

Mort and Ysabell travel to Keli''s palace, where the princess and Cutwell have organised a hasty coronation ceremony in the hope that Keli can be crowned queen before the alternate reality is destroyed. With the reality now too small for Albert''s spell, Mort and Ysabell save Keli and Cutwell from being destroyed with the alternate reality. They return to Death''s domain to find a furious Death waiting for them, the latter having learned of Mort''s actions from Albert. Death dismisses Mort and attempts to take the souls of Keli and Cutwell, but Mort challenges him to a duel for them. Though Death eventually wins the duel, he spares Mort''s life and sends him back to the Disc.

Death convinces the gods to change the original reality so that Keli rules in place of the Duke, who was inadvertently killed during Death and Mort''s duel. Mort and Ysabell – who have fallen in love over the course of the story – get married, and are made Duke and Duchess of Sto Helit by Keli, while Cutwell is made the Master of the Queen''s Bedchamber. Death attends Mort and Ysabell''s reception, where he warns Mort that he will have to make sure that the original Duke''s destiny is fulfilled, and presents him with the alternate reality he created, now shrunk to the size of a large pearl, before the two part on amicable terms. '),
('Dieser Roman führt die Nachtwache in ihrer ursprünglichen Besetzung mit ihrer verkommenen Berufsauffassung ein. Angeführt vom trinksüchtigen Hauptmann Samuel Mumm fristen Feldwebel Fred Colon und Korporal Cecil W. St. J. „Nobby“ Nobbs ihr peinliches Wachen-Dasein. Das ändert sich erst, als mit dem jungen Karotte Eisengießersohn ein neuer Rekrut aus den Spitzhornbergen die Szene betritt. Der zwei Meter große Adoptivzwerg ist voller Enthusiasmus, versteht nichts Metaphorisches und kennt das Gesetz in- und auswendig.

Während die Wache in ein neues Selbstverständnis hineinwächst, versucht eine Gruppe zänkischer Kleingeister unter der Führung des Obersten Größten Meisters die Monarchie in die Stadt zurückzubringen. Sie beschwören einen Großen Drachen, der ein wenig Terror verbreiten soll, um dann von einem wohl präparierten Helden besiegt zu werden. Anschließend würde der Stadtretter den Thron besteigen und, beraten vom Obersten Größten Meister, als Marionettenkönig regieren. Es gelingt tatsächlich, den Drachen zu beschwören, doch die Kreatur verselbständigt sich und übernimmt selbst die Macht. Die Stadt hat einen Drachenkönig.

Mumm und seine Leute müssen sich nun mit dem Drachen herumschlagen. Hilfreich in dieser Lage ist der Kontakt zu Lady Käsedick, einer Sumpfdrachenzüchterin. Mit ihrer Hilfe und mit der Unterstützung von Eroll, einem scheinbar degenerierten Sumpfdrachen, gelingt es der Wache schließlich, der Lage Herr zu werden. ',
'The story follows a plot by a secret brotherhood, the Unique and Supreme Lodge of the Elucidated Brethren of the Ebon Night, to overthrow the Patrician of Ankh-Morpork and install a puppet king, under the control of the Supreme Grand Master. Using a stolen magic book, they summon a dragon to strike fear into the people of Ankh-Morpork.

Once a suitable state of terror and panic has been created, the Supreme Grand Master proposes to put forth an "heir" to the throne, who will slay the dragon and rid the city of tyranny. It is the task of the Night Watch – Captain Vimes, Sergeant Colon, Corporal Nobbs, and new volunteer Carrot Ironfoundersson – to stop them, with some help from the Librarian of the Unseen University, an orangutan trying to get the stolen book back.

The Watch is generally regarded as a bunch of incompetents who walk around ringing their bells without accomplishing anything. Carrot''s arrival changes this; Whereas the existing officers are either cynical, incompetent, mildly crooked or all three, Carrot is honest, straightforward and idealistic. Additionally, he is 6''6" tall and enormously strong. Having memorized the Laws and Ordinances of the Cities of Ankh and Morpork, on his first day he tries to arrest the head of the Thieves'' Guild for theft (the Thieves'' Guild is permitted a quota of legally licensed thieving, a concept that the book of ancient Laws does not take into account). Brought up as a dwarf – dwarves are a literal, dutiful people – Carrot has an absolute dedication and conscientiousness that unnerve his colleagues who view them as bordering on the suicidal in the face of the reality of Ankh-Morpork life. Carrot''s policing style is reminiscent of traditional idealized portrayals of British police, but astoundingly, it actually seems to work.

Carrot''s enthusiasm strikes a chord with Vimes, who decides that the Watch should try to carry out its ostensible duties. Vimes begins investigating the dragon''s appearances, which leads to an acquaintance with Sybil Ramkin, a breeder of swamp dragons. Ramkin gives an underdeveloped dragon, Errol, to the Watch as a mascot.

The leader of the Elucidated Brethren is initially successful in controlling the dragon, but he has not accounted for the dragon''s own abilities. The banished dragon returns, and makes itself king of Ankh-Morpork (keeping the head of the Elucidated Brethren as its mouthpiece) and demands that the people of Ankh-Morpork bring it gold and regular virgin sacrifices, whilst preparing for an "ambitious and vigorous" foreign policy, aimed at subjugating the neighbours of Ankh Morpork.

Shortly after, Vimes is imprisoned in the same cell as the Patrician, who has been leading a relatively comfortable life with the help of the rats he uses as spies. The Librarian helps Vimes to escape and he runs to the aid of Sybil, who has been chosen as the first maiden to be sacrificed. The Watch''s swamp dragon, Errol, reorganises his digestive system to form a supersonic propulsion system and fights the king, eventually knocking it out of the sky with a shock wave. As the assembled crowd closes in on the king for the kill, Sybil tries to plead for the dragon''s life. Carrot instead places it under arrest, however Errol lets the dragon escape, revealing that the dragon is in fact female, the battle between the two being a courtship ritual.

Sam Vimes proceeds to arrest the Supreme Grand Master (Lupine Wonse, the Patrician''s secretary) but accidentally causes the man''s death when he tells Carrot to "throw the book at him." The man was attempting to summon another dragon, and dies from falling off a broken floor after being hit by the Laws and Ordinances of Ankh-Morpork.

The Patrician is reinstated as ruler of Ankh-Morpork, and offers the Watch anything they want as a reward. They ask only for a modest pay raise, a new tea kettle, and a dartboard. However, the Watch House at Treacle Mine Road was destroyed by the dragon. Lady Ramkin donates her childhood home at Pseudopolis Yard as the new Watch House.')
;
